% ============================================================
% 脚本名称: export_vq_to_cpp.m
% 功能: 将 MATLAB 训练好的 VQ 码书导出为 C++ 头文件 (.h)
% ============================================================

% 1. 检查变量是否存在
if ~exist('C_snore', 'var') || ~exist('C_noise', 'var')
    error('错误: 工作区中找不到 C_snore 或 C_noise 变量！请先运行训练代码。');
end

% 2. 打开文件准备写入
filename = 'vq_codebooks.h';
fid = fopen(filename, 'w');
if fid == -1
    error('错误: 无法创建文件 %s，请检查目录权限。', filename);
end

fprintf('正在生成 %s ...\n', filename);

% 3. 写入文件头 (Header Guards)
fprintf(fid, '// Auto-generated by MATLAB script\n');
fprintf(fid, '#ifndef VQ_CODEBOOKS_H\n');
fprintf(fid, '#define VQ_CODEBOOKS_H\n\n');

% ==================== 写入鼾声码书 (Snore) ====================
[rows, cols] = size(C_snore);
fprintf(fid, '// --- Snore Codebook ---\n');
fprintf(fid, 'const int SNORE_CLUSTERS = %d;\n', rows);
fprintf(fid, 'const int MFCC_DIM = %d;\n', cols);
fprintf(fid, 'const float snore_codebook[%d][%d] = {\n', rows, cols);

for i = 1:rows
    fprintf(fid, '    {');
    for j = 1:cols
        % 写入浮点数，保留6位小数
        if j < cols
            fprintf(fid, '%.6f, ', C_snore(i, j));
        else
            fprintf(fid, '%.6f', C_snore(i, j)); % 最后一个数后面不加逗号
        end
    end
    
    % 处理行尾符号
    if i < rows
        fprintf(fid, '},\n');
    else
        fprintf(fid, '}\n'); % 最后一行不加逗号
    end
end
fprintf(fid, '};\n\n');

% ==================== 写入噪音码书 (Noise) ====================
[rows, cols] = size(C_noise);
fprintf(fid, '// --- Noise Codebook ---\n');
fprintf(fid, 'const int NOISE_CLUSTERS = %d;\n', rows);
% 注意：这里假设维度和上面是一样的，就不重复定义 MFCC_DIM 了
fprintf(fid, 'const float noise_codebook[%d][%d] = {\n', rows, cols);

for i = 1:rows
    fprintf(fid, '    {');
    for j = 1:cols
        if j < cols
            fprintf(fid, '%.6f, ', C_noise(i, j));
        else
            fprintf(fid, '%.6f', C_noise(i, j));
        end
    end
    
    if i < rows
        fprintf(fid, '},\n');
    else
        fprintf(fid, '}\n');
    end
end
fprintf(fid, '};\n\n');

% 4. 写入文件尾
fprintf(fid, '#endif // VQ_CODEBOOKS_H\n');

% 5. 关闭文件
fclose(fid);

fprintf('成功！文件已保存在: %s\n', fullfile(pwd, filename));